# -*- coding: utf-8 -*-
"""Test&QUESTION 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKvZWkuvIB5SdGy6Sr_lVP27i4UReKgx
"""

def sumLignes(fichier):
    s = 0

    with open(fichier, "r") as file:
        lignes = file.readlines()

        for l in lignes:
            l = l.strip()
            nb = [char for char in l if char.isdigit()]
            if len(nb) >= 2:
                val = int(nb[0] + nb[-1])
                s += val
            elif len(nb) == 1:
                  val = int(nb[0] + nb[0])
                  s += val

    return s


fichier = "document.txt"
res = sumLignes(fichier)
print(f"La somme est : {res}")